# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='scale',
            field=models.FloatField(default=1, verbose_name='Scale px to m'),
            preserve_default=False,
        ),
    ]
